# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 674d8fd819ef06909635e32df950b804b5f7a5d038c5c5dcc812a92b6af7242a263ca9770b451ec9d62c9f6eed020bd536672d8ad6c35ad61c77031e881054c1

test:
  secret_key_base: a1277c272d6fc7763ce81d6dc9ce730c841addc9eeac2266ee0029feb310c03c9467cd3a2a5f629e68fa9f7a16aa69c11fe3957028c755975b7e7928b11b239c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
